version: "3.8"

services:
  Curso:
    container_name:
      "web-1"
    image:
      "JesusSedano/curso:latest"
    ports:
      - 8080:80
 
  Curso_Prod:    
    container_name:
      "prod-1"
    image:
      "JesusSedano/curso:1.3.0"
    ports:
      - 80:80